package actions

const PLAYER_HEALTH = 100
const MONSTER_HEALTH = 100

const PLAYER_ATTACK_MIN_DMG = 5
const PLAYER_ATTACK_MAX_DMG = 10

const PLAYER_SPECIAL_MIN_DMG = 10
const PLAYER_SPECIAL_MAX_DMG = 20

const PLAYER_HEALTH_MIN_VALUE = 5
const PLAYER_HEALTH_MAX_VALUE = 10

const MONSTER_ATTCK_MIN_DMG = 10
const MONSTER_ATTCK_MAX_DMG = 15
